name: nin-data-lastejobb

on:
  push:
    branches: [ master, updates ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm update
      - run: npm run download
      - run: npm run transform
      - name: Run deployment script
        run: ./.github/workflows/deploy.sh 
        shell: bash
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts.tar"
          tag: v_${{ github.run_number }}
      - name: post to slack
        run: ./.github/workflows/slack.sh ${{ secrets.POST_SLACK }}
        shell: bash
